# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Wedding"
license = "GPL-3.0"
licenselink = "https://github.com/YentlFrickx/hugo-theme-wedding/blob/main/LICENSE.md"
description = "Theme that can be used for a wedding website (for information, rsvp's)"
#homepage = "http://example.com/"
tags = ["responsive", "contact", "personal"]

min_version = "0.41.0"

[author]
  name = "Yentl Frickx"
  homepage = "https://yfrickx.be"

[original]
  name = "Wedding website"
  homepage = "http://wedding.rampatra.com/"
  repo = "https://github.com/rampatra/wedding-website"